apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: temp-demo-repo
spec:
  type: other
  lifecycle: unknown
  owner: pms
  coder:
    templateName: "devcontainers"
    mode: "auto"
    params:
      repo: "custom"
      region: "us-pittsburgh"
